"""Extract a continuous coasting take from the owner's MOV; requires ffmpeg.

Run: python3 scripts/prepare-freehub.py ~/Downloads/sound.MOV
Only the extracted audio is written to public/. The source video is unchanged.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import subprocess
import tempfile
import wave


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--start", type=float, default=2.0)
    parser.add_argument("--duration", type=float, help="Defaults to the remaining recording.")
    args = parser.parse_args()
    if not math.isfinite(args.start) or args.start < 0 or (args.duration is not None and (not math.isfinite(args.duration) or args.duration <= 0)):
        parser.error("Use a nonnegative start and a positive duration.")
    source = args.source.expanduser().resolve()
    with tempfile.TemporaryDirectory(prefix="endurace-audio-") as folder:
        extracted = Path(folder) / "extracted.wav"
        subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(source),
                        "-map", "0:a:0", "-vn",
                        "-c:a", "pcm_s16le", str(extracted)], check=True)
        with wave.open(str(extracted), "rb") as handle:
            rate = handle.getframerate()
            channels = handle.getnchannels()
            first_frame = round(args.start * rate)
            if first_frame >= handle.getnframes():
                parser.error("The sample start is past the end of the source recording.")
            frames = round(args.duration * rate) if args.duration is not None else handle.getnframes() - first_frame
            if first_frame + frames > handle.getnframes():
                parser.error("The source is shorter than the selected audio section.")
            handle.setpos(first_frame)
            pcm = handle.readframes(frames)
    destination = Path(__file__).resolve().parents[1] / "public" / "audio"
    destination.mkdir(parents=True, exist_ok=True)
    with wave.open(str(destination / "freehub.wav"), "wb") as handle:
        handle.setnchannels(channels)
        handle.setsampwidth(2)
        handle.setframerate(rate)
        handle.writeframes(pcm)
    audio_hash = hashlib.sha256((destination / "freehub.wav").read_bytes()).hexdigest()
    metadata = {
        "source": source.name,
        "sourceSha256": hashlib.sha256(source.read_bytes()).hexdigest(),
        "kind": "owner-recording",
        "sampleStartSeconds": args.start,
        "sampleDurationSeconds": frames / rate,
        "audioSeconds": frames / rate,
        "sampleRate": rate,
        "channels": channels,
        "audioSha256": audio_hash,
        "playbackRate": 1,
        "playbackMode": "single-coast",
        "processing": {"equalization": False, "normalization": False, "channelMixing": False, "resampling": False},
        "notes": "Unmodified native stereo coasting take, played once without looping. Its recorded cadence falls naturally; wheel speed also controls volume and the start position when enabling sound mid-coast.",
    }
    (destination / "freehub.json").write_text(json.dumps(metadata, indent=2) + "\n")
    config = destination.parents[1] / "src" / "lib" / "freehub-recording.ts"
    config.write_text('// Generated by scripts/prepare-freehub.py; the hash refreshes browser audio caches.\n'
                      f'export const FREEHUB_AUDIO_URL = "/audio/freehub.wav?v={audio_hash[:12]}";\n')
    (destination / "LICENSE.txt").write_text(
        "freehub.wav is derived from the owner's sound.MOV recording, supplied for this bike viewer.\n"
        "It is real recorded audio, not a synthetic demonstration. No CC0 licence is asserted.\n"
        "Processing and source hash are recorded in freehub.json. The source video is not distributed.\n")
    print(f"Owner coasting take: {frames/rate:.3f}s, {rate} Hz, {channels} channels, no loop -> {destination / 'freehub.wav'}")


if __name__ == "__main__":
    main()
